language: cpp
sudo: required
dist: trusty
services:
  - docker
compiler:
  - clang
  - gcc
os:
  - linux

before_install:
  - docker pull ubuntu:16.04
  - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/thezbyg/mcp2200ctl -td ubuntu:16.04 /bin/bash

install:
  - docker exec -ti travis-ci bash -c "apt-get update"
  - docker exec -ti travis-ci bash -c "apt-get install -y build-essential cmake linux-libc-dev git pkg-config libhidapi-dev libgtk-3-dev libudev-dev libjsoncpp-dev libboost-system-dev libboost-program-options-dev libboost-filesystem-dev libboost-test-dev"
  - if [[ "$CXX" == "g++" ]]; then docker exec -ti travis-ci bash -c "apt-get install -y g++"; fi
  - if [[ "$CXX" == "clang++" ]]; then docker exec -ti travis-ci bash -c "apt-get install -y clang"; fi

script:
  - docker exec -ti travis-ci bash -c "cd /thezbyg/mcp2200ctl && mkdir build && cd build && CC=${CC} CXX=${CXX} cmake .. && make"
after_script:
  - docker stop travis-ci

env:
  global:
    - LANG="en_US.UTF-8"
